### ISSUE TITLE
Dynamic resizing of CommentsTableViewCell not working

### ISSUE THREAD

**Issue by Pigpocket** [Pigpocket/Prizm#1]

**Comment by drumnkyle** [comment]
I messed around with this. You have a few different problems. I will list them here. I couldn't quite get it "working" because I'm not exactly sure what you want. Let me point out what I saw so you can figure out what you want to do.

1. You have a cell height specified in `CommentsViewControllerTableViewDelegate.swift`
2. You have a custom height set in the storyboard inspector on the row itself, so it won't resize if that is set
3. You have conflicting constraints with you wanting the User Stats Stack set to 65.5 height and bottom and top constrained to the superview. So, you need to figure out what you want in the layout here.

I'm confused why you don't have the text as a UILabel. Also, I'm confused why you don't put that label in a horizontal stack with the user stack. Those things might make this simpler, but I'm not positive.

Let me know if this helps or if you still are unsure where to go.

**Comment by Pigpocket** [comment]
Switched to SwiftUI for this controller
